server {
    listen 80;
    server_name raehal.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name raehal.com;

    ssl_certificate /etc/nginx/ssl/raehal.pem;
    ssl_certificate_key /etc/nginx/ssl/raehal-key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
